# Linear Regression

In [42]:
"""
jupyter nbconvert --to markdown lin_r.ipynb --output README.md
"""
import numpy as np
import pandas as pd


## DataSet

[Weight-Height](https://www.kaggle.com/sonalisingh1411/linear-regression-using-weight-height/data)

In [124]:
df = pd.read_csv('weight-height.csv')
df


Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

## Generating our Own data

For linear relationship : `y=βx+ϵ`

In [49]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Out

In [79]:
std = np.random.normal(loc=10, scale=2, size=(100,))
std
# start from 10, scale factor 2, 100 samples

array([12.66721241, 11.62345271, 12.46110036,  5.82999501, 11.22076022,
        6.94297689,  8.97012702, 10.88323543, 10.19553819,  8.92121895,
       10.94469877, 10.94680331, 12.67005676,  7.7555354 , 10.17803053,
       10.92607161, 10.31153695, 12.41214961, 10.58441622, 14.2965958 ,
       11.15329742,  8.07174661, 10.45349604, 13.66746546, 11.02359766,
        6.69701059,  6.64672214, 11.96548882, 13.00156791,  9.77528143,
        8.48051611,  9.47632562, 10.45727306,  9.49939793,  9.23977198,
       13.7340312 , 10.21142769, 11.96521351, 10.17735914, 10.1700133 ,
       11.31789284, 10.2313618 ,  9.13792624,  8.35729555,  7.69372331,
       10.49074144,  9.79714834, 12.7159697 ,  8.29924309, 11.26567017,
       11.64348039,  7.98545788,  9.462819  , 11.02805185,  7.10210677,
       10.78524151,  9.67167163,  6.443244  , 10.31915081,  9.92232538,
        9.0478629 ,  8.80796528,  9.99033003, 11.69590683,  9.91755777,
        7.64886517,  9.6758827 , 12.14662353,  9.10903232, 10.99

In [97]:
e = np.random.randn(100)
e


array([-0.08081075,  0.35412833, -0.59848323, -1.1046193 , -1.30302881,
       -1.07688227,  1.62269094, -0.52870761,  1.87681077, -1.49679116,
        0.92964647, -1.16286343,  0.85968225,  0.96031114, -1.44128916,
        1.76348083,  0.04501484,  0.43780959,  1.02776004,  0.05152385,
        0.5637066 ,  0.82487528, -0.8270986 , -0.41029055, -0.943235  ,
        0.16887113, -2.91326595,  0.27176334,  2.45139859, -0.68347263,
        2.66706514,  0.6654943 , -0.65318971, -0.57802598, -1.81142211,
       -0.33580496, -0.14320422, -0.29176043, -0.13365205,  0.97008864,
        0.07171166,  0.46427582, -0.25031636,  0.6488203 ,  1.29902815,
       -0.8764212 ,  0.65150035,  1.16661832,  1.69056275,  0.10909808,
        0.82441406, -0.61442329, -0.5344848 ,  0.60441955, -2.01898193,
        1.12592127,  0.32847319,  2.78673977,  0.62135014,  0.31794686,
        0.80253388,  1.51813088,  0.16198424,  1.26234114,  0.03517811,
        0.3799533 , -1.08697823,  2.10835911, -0.38462113, -0.08

In [118]:
x = np.random.randint(2,20,size=(100,))
x

array([14, 12,  2, 12, 16, 13, 12, 13,  2, 11, 10, 13,  3, 15,  8,  2, 11,
        4, 19, 19,  7,  5, 16, 12, 14, 19, 15, 13, 16, 18, 16,  6, 15,  6,
       19, 16, 14,  5,  6, 10,  2,  2,  5,  2,  8, 11, 13,  2,  3, 11, 19,
       18, 19,  7,  4,  9,  3,  2,  9, 13, 12,  7,  3, 11, 12, 10, 15, 14,
        9,  4,  6, 10,  8,  9,  4,  3, 10, 13,  6,  5, 13, 15,  8, 17,  6,
        6, 15,  5,  6,  4,  9,  8,  2,  7, 19,  5, 14,  6, 15, 11])

In [119]:
y = x * 2 + e
y

array([27.91918925, 24.35412833,  3.40151677, 22.8953807 , 30.69697119,
       24.92311773, 25.62269094, 25.47129239,  5.87681077, 20.50320884,
       20.92964647, 24.83713657,  6.85968225, 30.96031114, 14.55871084,
        5.76348083, 22.04501484,  8.43780959, 39.02776004, 38.05152385,
       14.5637066 , 10.82487528, 31.1729014 , 23.58970945, 27.056765  ,
       38.16887113, 27.08673405, 26.27176334, 34.45139859, 35.31652737,
       34.66706514, 12.6654943 , 29.34681029, 11.42197402, 36.18857789,
       31.66419504, 27.85679578,  9.70823957, 11.86634795, 20.97008864,
        4.07171166,  4.46427582,  9.74968364,  4.6488203 , 17.29902815,
       21.1235788 , 26.65150035,  5.16661832,  7.69056275, 22.10909808,
       38.82441406, 35.38557671, 37.4655152 , 14.60441955,  5.98101807,
       19.12592127,  6.32847319,  6.78673977, 18.62135014, 26.31794686,
       24.80253388, 15.51813088,  6.16198424, 23.26234114, 24.03517811,
       20.3799533 , 28.91302177, 30.10835911, 17.61537887,  7.91

In [120]:
df = pd.DataFrame({'time_spent': x, 'performance': y})
df

time_spent  performance
0           14    27.919189
1           12    24.354128
2            2     3.401517
3           12    22.895381
4           16    30.696971
..         ...          ...
95           5     8.494807
96          14    27.638602
97           6    12.594343
98          15    29.893384
99          11    21.954920

[100 rows x 2 columns]

In [115]:
randomNums = np.random.normal(scale=1, size=100)
randomInts = np.floor(randomNums)
randomInts


array([ 0., -1., -2.,  0., -1.,  0.,  1.,  0., -2., -1.,  0.,  0., -2.,
       -1., -1., -2.,  0., -1.,  0., -1., -1.,  1.,  0.,  1., -1.,  0.,
        0.,  0., -2., -2.,  0., -2., -1., -1.,  0., -2.,  0.,  0.,  0.,
       -1.,  0., -3., -1., -1., -1.,  0.,  1.,  0.,  0.,  0., -1.,  0.,
       -1.,  1.,  1., -2., -2., -1., -1., -1.,  1.,  1., -2., -1., -1.,
       -1., -1.,  0.,  0., -1., -3., -2.,  1., -1., -2.,  0., -2., -1.,
       -1.,  0.,  0., -2.,  1., -1., -1.,  0.,  0., -1., -1.,  1., -2.,
       -1.,  0., -2., -1.,  1.,  0.,  0.,  1., -1.])